version: "2.1"

services:
  jupyter:
    # Name of the container, rename to whatever you want.
    container_name: jupyter-mito
    # Points to the jupyter folder in this repository that contains the Dockerfile
    build: jupyter
    # Tie ports 8888 on the container and the host computer, so we can access the Jupyter notebook.
    ports:
      - 8888:8888
    # The Jupyter notebook looks to the /home/jovyan folder (on the container) for files. So map our demo folder to that volume.
    volumes:
      - "./demo:/home/jovyan"
    # The command that starts the notebook when the container boots up.
    command: "start-notebook.sh"
    # Run as root, so we can install Pip libraries.
    user: root
    # Set env variables
    environment:
      # Grant sudo so we can run pip commands, if needed.
      GRANT_SUDO: 'yes'
      # Enable lab needs to be set to yes in order for JupyterLabs to be installed - which is required by Mito.
      JUPYTER_ENABLE_LAB: 'yes'